version: "3.8"

services:
  api:
    container_name: "api"
    restart: always
    ports: 
      - "8000:8000"
    build: .
    volumes:
    - .:/app
    command: python /app/manage.py runserver 0.0.0.0:8000