# Generated by Django 4.0 on 2021-12-26 07:51

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('name', models.CharField(max_length=512)),
                ('address', models.TextField(null=True)),
                ('timetable', models.TextField(null=True)),
            ],
            options={
                'db_table': 'libraries',
            },
        ),
    ]
